### PR TITLE
Add single file corpus types (json, csv, generic)

### PR DESCRIPTION
**Pull request by chfin**
Introduces three new classes:
- `SingleFileCorpus`: takes a `file` parameter and reads all data from that file.
  `.files()` returns a singleton list containing only the file.
  `.data()` returns a `Path` object to the file.
- `JSONFileCorpus`: like `SingleFileCorpus`, but `.data()` takes `json.load` parameters and returns parsed JSON.
- `CSVFileCorpus`: like `SingleFileCorpus`, but `.data()` takes `pandas.read_csv` parameters and returns a dataframe.

Single-file corpora for other file types may be added and only have to override `.data()`.

An example of a `JSONFileCorpus` is the [JHT](https://github.com/DCMLab/JazzHarmonyTreebank/), which is added to `DCML_corpora.ini`.

### CODE REVIEW

**Comment by chfin** [comment]
I now changed the handling of keyword arguments. Instead of remembering all keywords during initialization, only explicitly defined keywords are considered. In particular:
- `SingleFileCorpus` and its subclasses consider the `corpus_kwargs` keyword, which takes a dictionary of keywords that may be used in `data` but is kept through the lifetime of the corpus object. All args kept here can be overriden by the args given to `data()`
- `CSVFileCorpus` takes the `sep` keyword, which indicates the separator character.

In order to support tabs as separators, the value provided for `sep` is parsed as a string literal if it starts with a quote. This allows us write something like this in the config:
```
sep = "\t"
```
The value is read as `'"\t"'` but then parsed as `'\t'`, because it starts with a double quote (single quotes work too).
This is basically just a hack to work around the limitations of the configparser format, which doesn't provide a way to escape special characters. In case we switch to a different config format, we should remove this again.

**Comment by robert-lieck** [comment]
I can't do a thorough code review at the moment, but this sounds good!

**Comment by chfin** [comment]
Cool! Does that mean I should merge this or do you want to have a better look before?

**Comment by chfin** [comment]
I added the following things now:
- a `file` access method that downloads a single file
- `gz`, `xz`, and `bz2` access methods that download and extract single compressed files
- a corpus type `JSONLinesCorpus` that can read a single JSON Lines file (JSON objects separated by line breaks)
- entries for the [MTC and Essen Folkson "melodic features" corpora](https://zenodo.org/record/3551003), which use the JSONL format

**Pull request merged**
